services:
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - hypertube-network
    restart: always
    
  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - "3333:3333"
    networks:
      - hypertube-network
    environment:
      - HOST=0.0.0.0
    restart: always

  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - hypertube-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hypertube
    restart: always
    
networks:
  hypertube-network:
    driver: bridge
